//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsBook.Domain.DataStructs
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactsBookEntities : DbContext
    {
        public ContactsBookEntities()
            : base("name=ContactsBookEntities")
        {
        }

        public ContactsBookEntities(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<EMail> EMails { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
    }
}
