//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsBook.Domain.DataStructs
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public long ID { get; set; }
        public string Number { get; set; }
        public long ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
